# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core.sparse_data.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/core.sparse_data.ipynb 2
import torch as th
from skimage.filters import gaussian
import numpy as np
import h5py 
from fastcore.basics import *
